# Generated by Django 2.0.6 on 2019-09-26 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190926_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
