# Generated by Django 2.0.6 on 2019-09-29 11:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190926_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='博客正文'),
        ),
    ]
