# Generated by Django 2.0.6 on 2019-09-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190929_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_blogs', to='blogs.Category', verbose_name='分类'),
        ),
    ]
